version: "3"
services:
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: ${TZ}
    restart: always
    networks:
      - default

  php56:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP56_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
        TZ: ${TZ}
    container_name: php56
    expose:
      - 9000
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP56_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
      - ${SUPERVISOR_LOG}:/var/log/supervisor/:rw
      - ${SUPERVISOR_CONFIG}php56-fpm.ini:/etc/supervisor/conf.d/php-fpm.ini:rw
      - ${SUPERVISOR_CONF_FILE}:/etc/supervisor/supervisord.conf:ro
    restart: always
    command:
     - /bin/sh
     - -c
     - |
        supervisord -n -c /etc/supervisor/supervisord.conf
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php56_cli:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP56_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
        TZ: ${TZ}
    container_name: php56_cli
    deploy:
        resources:
            limits:
                cpus: '0.50'
                memory: 512M
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
      - ${SUPERVISOR_LOG}:/var/log/supervisor/:rw
      - ${SUPERVISOR_CONFIG}php56-cli.ini:/etc/supervisor/conf.d/php-cli.ini:rw
      - ${SUPERVISOR_CONF_FILE}:/etc/supervisor/supervisord.conf:ro
    restart: always
    command:
     - /bin/sh
     - -c
     - |
        supervisord -n -c /etc/supervisor/supervisord.conf
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: ${TZ}
    container_name: php
    expose:
      - 9000
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CACERT_DIR}:/usr/local/etc/php/cacert
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
      - ${SUPERVISOR_LOG}:/var/log/supervisor/:rw
      - ${SUPERVISOR_CONFIG}php-fpm.ini:/etc/supervisor/conf.d/php-fpm.ini:rw
      - ${SUPERVISOR_CONF_FILE}:/etc/supervisor/supervisord.conf:ro
    restart: always
    command:
     - /bin/sh
     - -c
     - |
        supervisord -n -c /etc/supervisor/supervisord.conf
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php_cli:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: ${TZ}
    container_name: php_cli
    deploy:
        resources:
            limits:
                cpus: '0.50'
                memory: 512M
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CACERT_DIR}:/usr/local/etc/php/cacert
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
      - ${SUPERVISOR_LOG}:/var/log/supervisor/:rw
      - ${SUPERVISOR_CONFIG}php-cli.ini:/etc/supervisor/conf.d/php-cli.ini:rw
      - ${SUPERVISOR_CONF_FILE}:/etc/supervisor/supervisord.conf:ro
    restart: always
    command:
     - /bin/sh
     - -c
     - |
        supervisord -n -c /etc/supervisor/supervisord.conf
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  golang:
    build:
      context: ./services/golang
    container_name: golang
    ports:
      - "${GOLANG_HOST_PORT}:8088"
    volumes:
      - ${SOURCE_DIR}/go:/go:rw
    networks:
      - default
    environment:
      TZ: ${TZ}
    tty: true

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: ${TZ}

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: ${TZ}
    networks:
      - default

  memcached:
    image: memcached:${MEMCACHED_VERSION}
    container_name: memcached
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"      
    restart: always
    environment:
       MEMCACHED_CACHE_SIZE: "${MEMCACHED_CACHE_SIZE}"
    networks:
      - default

networks:
  default:
